import { beforeAll, describe, expect, it } from "vitest";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { hexToBytes } from "@noble/hashes/utils";
import { finalizeEvent, getPublicKey } from "nostr-tools";

import { AppKeys } from "../src/AppKeys";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface AppKeysDeviceVector {
  identity_pubkey: string;
  created_at: number;
}

interface AppKeysLabelVector {
  identity_pubkey: string;
  device_label?: string;
  client_label?: string;
  updated_at: number;
}

interface AppKeysInteropVectors {
  description: string;
  owner_secret_hex: string;
  owner_pubkey: string;
  devices: AppKeysDeviceVector[];
  expected_labels: AppKeysLabelVector[];
  signed_event: {
    id: string;
    pubkey: string;
    created_at: number;
    kind: number;
    tags: string[][];
    content: string;
    sig: string;
  };
}

const OWNER_SECRET_HEX = "10".repeat(32);
const DEVICE_ONE_SECRET_HEX = "20".repeat(32);
const DEVICE_TWO_SECRET_HEX = "30".repeat(32);

function getVectorsPath(filename: string): string {
  return path.join(__dirname, "../../test-vectors", filename);
}

describe("AppKeys Interop Vector Generation", () => {
  let vectors: AppKeysInteropVectors;

  beforeAll(() => {
    const ownerSecret = hexToBytes(OWNER_SECRET_HEX);
    const ownerPubkey = getPublicKey(ownerSecret);
    const deviceOnePubkey = getPublicKey(hexToBytes(DEVICE_ONE_SECRET_HEX));
    const deviceTwoPubkey = getPublicKey(hexToBytes(DEVICE_TWO_SECRET_HEX));

    const appKeys = new AppKeys([
      { identityPubkey: deviceOnePubkey, createdAt: 100 },
      { identityPubkey: deviceTwoPubkey, createdAt: 200 },
    ]);
    appKeys.setDeviceLabels(
      deviceOnePubkey,
      {
        deviceLabel: "Office MacBook",
        clientLabel: "Iris Desktop",
      },
      1000
    );
    appKeys.setDeviceLabels(
      deviceTwoPubkey,
      {
        deviceLabel: "Phone",
        clientLabel: "Iris iOS",
      },
      1001
    );

    const signedEvent = finalizeEvent(appKeys.getEvent(ownerSecret), ownerSecret);
    vectors = {
      description: "AppKeys label vectors generated by TypeScript",
      owner_secret_hex: OWNER_SECRET_HEX,
      owner_pubkey: ownerPubkey,
      devices: [
        { identity_pubkey: deviceOnePubkey, created_at: 100 },
        { identity_pubkey: deviceTwoPubkey, created_at: 200 },
      ],
      expected_labels: [
        {
          identity_pubkey: deviceOnePubkey,
          device_label: "Office MacBook",
          client_label: "Iris Desktop",
          updated_at: 1000,
        },
        {
          identity_pubkey: deviceTwoPubkey,
          device_label: "Phone",
          client_label: "Iris iOS",
          updated_at: 1001,
        },
      ],
      signed_event: {
        id: signedEvent.id,
        pubkey: signedEvent.pubkey,
        created_at: signedEvent.created_at,
        kind: signedEvent.kind,
        tags: signedEvent.tags,
        content: signedEvent.content,
        sig: signedEvent.sig,
      },
    };

    const outputPath = getVectorsPath("ts-app-keys-vectors.json");
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, JSON.stringify(vectors, null, 2));
    console.log(`Generated AppKeys vectors at ${outputPath}`);
  });

  it("TS can decrypt its own AppKeys label vectors", () => {
    const ownerSecret = hexToBytes(vectors.owner_secret_hex);
    const parsed = AppKeys.fromEvent(vectors.signed_event as any, ownerSecret);

    expect(parsed.getAllDevices()).toHaveLength(2);
    expect(parsed.getDeviceLabels(vectors.expected_labels[0].identity_pubkey)).toEqual({
      deviceLabel: "Office MacBook",
      clientLabel: "Iris Desktop",
      updatedAt: 1000,
    });
    expect(parsed.getDeviceLabels(vectors.expected_labels[1].identity_pubkey)).toEqual({
      deviceLabel: "Phone",
      clientLabel: "Iris iOS",
      updatedAt: 1001,
    });
    expect(vectors.signed_event.content).not.toContain("Office MacBook");
    expect(vectors.signed_event.content).not.toContain("Iris Desktop");
  });
});

describe("Rust-generated AppKeys vectors", () => {
  it("TypeScript can decrypt Rust AppKeys label vectors", () => {
    const vectorPath = getVectorsPath("rust-app-keys-vectors.json");

    if (!fs.existsSync(vectorPath)) {
      console.log("Rust AppKeys vectors not found at", vectorPath, "skipping...");
      console.log(
        "Run `cargo test -p nostr-double-ratchet --test app_keys_interop` to generate them."
      );
      return;
    }

    const vectors: AppKeysInteropVectors = JSON.parse(
      fs.readFileSync(vectorPath, "utf-8")
    );
    const ownerSecret = hexToBytes(vectors.owner_secret_hex);

    const parsedWithoutKey = AppKeys.fromEvent(vectors.signed_event as any);
    expect(parsedWithoutKey.getAllDevices()).toHaveLength(vectors.devices.length);
    for (const label of vectors.expected_labels) {
      expect(parsedWithoutKey.getDeviceLabels(label.identity_pubkey)).toBeUndefined();
    }

    const parsedWithKey = AppKeys.fromEvent(vectors.signed_event as any, ownerSecret);
    for (const label of vectors.expected_labels) {
      expect(parsedWithKey.getDeviceLabels(label.identity_pubkey)).toEqual({
        deviceLabel: label.device_label,
        clientLabel: label.client_label,
        updatedAt: label.updated_at,
      });
    }
  });
});
