/**
 * Group roster fact interop test.
 *
 * - Generates TS fact-rumor vectors for Rust to verify.
 * - Verifies Rust-generated fact-rumor vectors when present.
 */
import { describe, it, expect, beforeAll } from "vitest";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { getEventHash } from "nostr-tools";

import {
  buildGroupRosterFactEvent,
  GROUP_ROSTER_FACT_KIND,
  GROUP_ROSTER_FACT_TYPE,
  parseGroupRosterFactRumor,
  type GroupData,
  type GroupRosterFactRumor,
} from "../src/Group";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ALICE = "aaaa".repeat(16);
const BOB = "bbbb".repeat(16);
const CAROL = "cccc".repeat(16);
const DEVICE = "dddd".repeat(16);

interface GroupRosterFactVector {
  description: string;
  event: GroupRosterFactRumor;
  expected: {
    group_id: string;
    name: string;
    created_by: string;
    members: string[];
    admins: string[];
    revision: number;
    created_at: number;
    updated_at: number;
  };
}

function vectorPath(name: string): string {
  return path.join(__dirname, "../../test-vectors", name);
}

function group(): GroupData {
  return {
    id: "interop-test-group-id",
    name: "Interop Test Group",
    description: "Roster facts across TS and Rust",
    members: [ALICE, BOB, CAROL],
    admins: [ALICE],
    createdAt: 1_700_000_000,
    accepted: true,
  };
}

function buildVector(): GroupRosterFactVector {
  const event: GroupRosterFactRumor = {
    ...buildGroupRosterFactEvent(group(), {
      signerPubkey: DEVICE,
      revision: 3,
      createdBy: ALICE,
      updatedAt: 1_700_000_123,
      eventCreatedAt: 1_700_000_124,
      protocol: "sender_key_v1",
    }),
    id: "",
  };
  event.id = getEventHash(event);
  return {
    description: "Group roster fact vector generated by TypeScript",
    event,
    expected: {
      group_id: "interop-test-group-id",
      name: "Interop Test Group",
      created_by: ALICE,
      members: [ALICE, BOB, CAROL].sort(),
      admins: [ALICE],
      revision: 3,
      created_at: 1_700_000_000,
      updated_at: 1_700_000_123,
    },
  };
}

function assertVector(vector: GroupRosterFactVector): void {
  expect(vector.event.kind).toBe(GROUP_ROSTER_FACT_KIND);
  expect(vector.event.content).toBe("");
  expect(vector.event.tags).toContainEqual(["type", GROUP_ROSTER_FACT_TYPE]);
  const parsed = parseGroupRosterFactRumor(vector.event);
  expect(parsed.groupId).toBe(vector.expected.group_id);
  expect(parsed.group.name).toBe(vector.expected.name);
  expect(parsed.createdBy).toBe(vector.expected.created_by);
  expect(parsed.group.members).toEqual(vector.expected.members);
  expect(parsed.group.admins).toEqual(vector.expected.admins);
  expect(parsed.revision).toBe(vector.expected.revision);
  expect(parsed.group.createdAt).toBe(vector.expected.created_at);
  expect(parsed.updatedAt).toBe(vector.expected.updated_at);
}

describe("Group roster fact interop vectors", () => {
  let vectors: GroupRosterFactVector;

  beforeAll(() => {
    vectors = buildVector();
    const outputPath = vectorPath("ts-group-roster-fact-vectors.json");
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, JSON.stringify(vectors, null, 2));
  });

  it("TypeScript parses its generated group roster fact rumor", () => {
    assertVector(vectors);
  });

  it("TypeScript parses Rust-generated group roster fact rumor", () => {
    const outputPath = vectorPath("rust-group-roster-fact-vectors.json");
    if (!fs.existsSync(outputPath)) {
      console.log("Rust group roster fact vectors not found, skipping...");
      return;
    }

    const rustVector = JSON.parse(
      fs.readFileSync(outputPath, "utf-8"),
    ) as GroupRosterFactVector;
    assertVector(rustVector);
  });
});
