import { beforeAll, describe, expect, it } from "vitest";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { hexToBytes } from "@noble/hashes/utils";
import { getPublicKey } from "nostr-tools";

import {
  buildSenderKeyRepairRequestRumor,
  parseSenderKeyRepairRequestRumor,
  type SenderKeyRepairRequest,
} from "../src/SenderKeyRepair";
import type { Rumor } from "../src/types";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const REQUESTER_DEVICE_SECRET_HEX = "11".repeat(32);
const SENDER_EVENT_SECRET_HEX = "33".repeat(32);
const CREATED_AT_MS = 12_000;

interface SenderKeyRepairVectors {
  description: string;
  requester_device_pubkey: string;
  encoded_at_ms: number;
  request: SenderKeyRepairRequest;
  repair_request_event: Rumor;
}

describe("SenderKeyRepair interop vectors", () => {
  let vectors: SenderKeyRepairVectors;

  beforeAll(() => {
    const outputPath = path.join(
      __dirname,
      "../../test-vectors/ts-sender-key-repair-vectors.json",
    );

    const shouldRegenerate =
      process.env.REGENERATE_VECTORS === "true" || !fs.existsSync(outputPath);

    if (!shouldRegenerate) {
      vectors = JSON.parse(fs.readFileSync(outputPath, "utf-8")) as SenderKeyRepairVectors;
      return;
    }

    const requesterDevicePubkey = getPublicKey(hexToBytes(REQUESTER_DEVICE_SECRET_HEX));
    const senderEventPubkey = getPublicKey(hexToBytes(SENDER_EVENT_SECRET_HEX));
    const request: SenderKeyRepairRequest = {
      groupId: "group-1",
      senderEventPubkey,
      keyId: 7,
      messageNumber: 42,
      requiredRevision: 9,
      createdAt: 13,
    };

    vectors = {
      description: "SenderKeyRepair 10447 request vector generated by TypeScript",
      requester_device_pubkey: requesterDevicePubkey,
      encoded_at_ms: CREATED_AT_MS,
      request,
      repair_request_event: buildSenderKeyRepairRequestRumor(
        request,
        requesterDevicePubkey,
        CREATED_AT_MS,
      ),
    };

    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, JSON.stringify(vectors, null, 2));
    console.log(`Generated sender-key repair vectors at ${outputPath}`);
  });

  it("TypeScript can parse its own repair request vector", () => {
    expect(vectors.repair_request_event.pubkey).toBe(vectors.requester_device_pubkey);
    expect(parseSenderKeyRepairRequestRumor(vectors.repair_request_event)).toEqual(
      vectors.request,
    );
  });
});

describe("Rust-generated SenderKeyRepair vectors", () => {
  it("TypeScript can parse Rust repair request vectors when present", () => {
    const vectorPath = path.join(
      __dirname,
      "../../test-vectors/rust-sender-key-repair-vectors.json",
    );

    if (!fs.existsSync(vectorPath)) {
      console.log("Rust sender-key repair vectors not found, skipping...");
      return;
    }

    const vectors = JSON.parse(fs.readFileSync(vectorPath, "utf-8")) as SenderKeyRepairVectors;
    expect(parseSenderKeyRepairRequestRumor(vectors.repair_request_event)).toEqual(
      vectors.request,
    );
  });
});
