use nostr::JsonUtil;
use nostr::{Keys, SecretKey};
use nostr_double_ratchet::Result;
use nostr_double_ratchet_nostr::{utils::pubkey_from_hex, AppKeys, DeviceEntry};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Serialize, Deserialize)]
struct AppKeysInteropVectors {
    description: String,
    owner_secret_hex: String,
    owner_pubkey: String,
    devices: Vec<AppKeysDeviceVector>,
    expected_labels: Vec<AppKeysLabelVector>,
    signed_event: serde_json::Value,
}

#[derive(Debug, Serialize, Deserialize)]
struct AppKeysDeviceVector {
    identity_pubkey: String,
    created_at: u64,
}

#[derive(Debug, Serialize, Deserialize)]
struct AppKeysLabelVector {
    identity_pubkey: String,
    device_label: Option<String>,
    client_label: Option<String>,
    updated_at: u64,
}

fn get_test_vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("test-vectors")
}

fn hex_to_bytes32(hex_str: &str) -> [u8; 32] {
    let bytes = hex::decode(hex_str).expect("Invalid hex");
    let mut arr = [0u8; 32];
    arr.copy_from_slice(&bytes);
    arr
}

#[test]
fn test_generate_rust_app_keys_vectors() -> Result<()> {
    let owner_secret_hex = "1010101010101010101010101010101010101010101010101010101010101010";
    let device_one_secret_hex = "2020202020202020202020202020202020202020202020202020202020202020";
    let device_two_secret_hex = "3030303030303030303030303030303030303030303030303030303030303030";

    let owner_secret = hex_to_bytes32(owner_secret_hex);
    let owner_keys = Keys::new(SecretKey::from_slice(&owner_secret)?);
    let device_one_pubkey = Keys::new(SecretKey::from_slice(&hex_to_bytes32(
        device_one_secret_hex,
    ))?)
    .public_key();
    let device_two_pubkey = Keys::new(SecretKey::from_slice(&hex_to_bytes32(
        device_two_secret_hex,
    ))?)
    .public_key();

    let mut app_keys = AppKeys::new(vec![
        DeviceEntry::new(device_one_pubkey, 100),
        DeviceEntry::new(device_two_pubkey, 200),
    ]);
    app_keys.set_device_labels(
        device_one_pubkey,
        Some("Office MacBook".to_string()),
        Some("Iris Desktop".to_string()),
        Some(1000),
    );
    app_keys.set_device_labels(
        device_two_pubkey,
        Some("Phone".to_string()),
        Some("Iris iOS".to_string()),
        Some(1001),
    );

    let signed_event = app_keys
        .get_encrypted_event(&owner_keys)?
        .sign_with_keys(&owner_keys)?;

    let vectors = AppKeysInteropVectors {
        description: "AppKeys label vectors generated by Rust".to_string(),
        owner_secret_hex: owner_secret_hex.to_string(),
        owner_pubkey: owner_keys.public_key().to_hex(),
        devices: vec![
            AppKeysDeviceVector {
                identity_pubkey: device_one_pubkey.to_hex(),
                created_at: 100,
            },
            AppKeysDeviceVector {
                identity_pubkey: device_two_pubkey.to_hex(),
                created_at: 200,
            },
        ],
        expected_labels: vec![
            AppKeysLabelVector {
                identity_pubkey: device_one_pubkey.to_hex(),
                device_label: Some("Office MacBook".to_string()),
                client_label: Some("Iris Desktop".to_string()),
                updated_at: 1000,
            },
            AppKeysLabelVector {
                identity_pubkey: device_two_pubkey.to_hex(),
                device_label: Some("Phone".to_string()),
                client_label: Some("Iris iOS".to_string()),
                updated_at: 1001,
            },
        ],
        signed_event: serde_json::from_str(&signed_event.as_json()).unwrap(),
    };

    let output_path = get_test_vectors_path().join("rust-app-keys-vectors.json");
    fs::create_dir_all(output_path.parent().unwrap()).ok();
    fs::write(
        &output_path,
        serde_json::to_string_pretty(&vectors).unwrap(),
    )
    .expect("Failed to write vectors");

    println!("Generated Rust AppKeys vectors at {:?}", output_path);

    Ok(())
}

#[test]
fn test_parse_typescript_app_keys_vectors() -> Result<()> {
    let vectors_path = get_test_vectors_path().join("ts-app-keys-vectors.json");

    if !vectors_path.exists() {
        println!(
            "TypeScript AppKeys vectors not found at {:?}, skipping...",
            vectors_path
        );
        println!("Run `pnpm vitest run tests/AppKeys.interop.test.ts` in ts/ to generate them.");
        return Ok(());
    }

    let content = fs::read_to_string(&vectors_path).expect("Failed to read vectors");
    let vectors: AppKeysInteropVectors =
        serde_json::from_str(&content).expect("Failed to parse vectors");

    let owner_secret = hex_to_bytes32(&vectors.owner_secret_hex);
    let owner_keys = Keys::new(SecretKey::from_slice(&owner_secret)?);
    assert_eq!(owner_keys.public_key().to_hex(), vectors.owner_pubkey);

    let event: nostr::Event =
        serde_json::from_value(vectors.signed_event.clone()).expect("Failed to parse signed event");
    assert!(event.verify().is_ok());

    let parsed_public = AppKeys::from_event(&event)?;
    assert_eq!(parsed_public.get_all_devices().len(), vectors.devices.len());
    for label in &vectors.expected_labels {
        let pubkey = pubkey_from_hex(&label.identity_pubkey).unwrap();
        assert!(parsed_public.get_device_labels(&pubkey).is_none());
    }

    let parsed_with_labels = AppKeys::from_event_with_labels(&event, &owner_keys)?;
    for label in &vectors.expected_labels {
        let pubkey = pubkey_from_hex(&label.identity_pubkey).unwrap();
        let parsed = parsed_with_labels
            .get_device_labels(&pubkey)
            .expect("missing device labels");
        assert_eq!(parsed.device_label, label.device_label);
        assert_eq!(parsed.client_label, label.client_label);
        assert_eq!(parsed.updated_at, label.updated_at);
    }

    Ok(())
}
